FROM node:22-alpine AS build
WORKDIR /client
COPY package*.json ./
RUN npm ci
COPY . /client
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
