# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/thefootlol.com
cert = /etc/letsencrypt/live/thefootlol.com/cert.pem
privkey = /etc/letsencrypt/live/thefootlol.com/privkey.pem
chain = /etc/letsencrypt/live/thefootlol.com/chain.pem
fullchain = /etc/letsencrypt/live/thefootlol.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a2ee4f3ddcdab5fa0da5491e96fa3776
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
