# renew_before_expiry = 30 days
version = 1.29.0
archive_dir = /etc/letsencrypt/archive/thefootlol.com
cert = /etc/letsencrypt/live/thefootlol.com/cert.pem
privkey = /etc/letsencrypt/live/thefootlol.com/privkey.pem
chain = /etc/letsencrypt/live/thefootlol.com/chain.pem
fullchain = /etc/letsencrypt/live/thefootlol.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8c27951c6495c834f34672189f76aa35
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = rsa
