version: "3"
services:
  game-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: game-client
    container_name: game-client
    command: >
      bash -c "npm run start"
    volumes:
      - ./client:/client
    ports:
      - "8000:3000"
    depends_on:
      - game-server
    restart: always
  game-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    image: game-server
    container_name: game-server
    volumes:
      - ./server:/server
    ports:
      - "8081:3000"
    restart: always
