version: "3"
services:
  game-nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: game-nginx
    container_name: game-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.pro.conf:/etc/nginx/nginx.conf
    depends_on:
      - game-server
    restart: always
  game-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: game-server
    container_name: game-server
    restart: always
